#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# creates a symbolic link (-s option) between the nginx configuration file
# and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminate the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
